# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: A
    jobs:
      - job: A1
        steps:
          - script: echo A1
      - job: A2
        steps:
          - script: echo A2
            
pool:
  vmImage: ubuntu-latest

  Steps: 
  - task: NodeTool@0
    inputs:
      versionSpec: '6.x'
      displayName: 'Install node.js'

# install dependencies
  - script: npm install
    displayName: npm install

  - script: npm run build
    displayName: 'npm build'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
