triger:
  - master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    'Node 16':
      versionSpec: '16.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(versionSpec)
    displayName: Install node

  # install dependencies
  - script: npm install
    displayName: npm install

  # build
  - script: npm run build
    displayName: npm run build

  - script: npm run units
    displayName: Run unit tests
