trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install node'

  # install dependencies
  - script: |
      npm install
    displayName: 'npm install'

  # build
  - script: |
        npm run start
    displayName: 'npm run start'
